--- # ---

# kind: ConfigMap
# apiVersion: v1
# metadata:
# name: command-cm
# namespace: default
# labels:
# app: autovoice
# service: command
# data:
# ASPNETCORE_ENVIRONMENT: Development
# ASPNETCORE_URLS: http://0.0.0.0:80
# IdentityUrl: http://identity-api
# IdentityUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30008
# SeqServerUrl: http://seq

kind: Deployment
apiVersion: apps/v1
metadata:
  name: command
  namespace: default
  labels:
    app: command
    service: command-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: command-service
  template:
    metadata:
      labels:
        app: command
        service: command-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "commandapi"
        dapr.io/app-port: "5004"
        dapr.io/config: "tracing"
        dapr.io/log-as-json: "true"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: command-api         
          image: docker.na1.hsdp.io/hosting/platform/autovoiceui/command-service:1.0.13
          ports:             
           - containerPort: 5004

---
apiVersion: v1
kind: Service
metadata:
  name: command-api
  namespace: default
  labels:
    app: command
    service: command-service
spec:
  type: NodePort
  ports:
    - port: 5004
      targetPort: 5004
      nodePort: 30005
      protocol: TCP
      name: http
    - port: 3500
      targetPort: 3500
      nodePort: 30777
      protocol: TCP
      name: dapr
  selector:
    service: command-service
