apiVersion: apps/v1
kind: Deployment
metadata:
  name: command
  labels:
    app: command
    service: command-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command
      service: command-service
  template:
    metadata:
      labels:
        app: command
        service: command-service
    spec:
      serviceAccountName: autovoice-cmd
      containers:
      - name: command-api
        image: docker.na1.hsdp.io/hosting/platform/autovoiceui/command-service:1.0.9
        ports: 
         - containerPort: 5004
