apiVersion: v1
kind: Service
metadata:
  name: command-api
  namespace: default
  labels:
    app: command
    service: command-service
spec:
  type: NodePort
  ports:
    - port: 5004
      targetPort: 5004
      nodePort: 30005
      protocol: TCP
      name: http
    - port: 3500
      targetPort: 3500
      nodePort: 30777
      protocol: TCP
      name: dapr
  selector:
    service: command-service
